// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var Swiper = require("swiper");

Curry._2(document.addEventListener, "DOMContentLoaded", (function (_event) {
        console.log(_event);
        console.log(Swiper.Swiper);
        var a = (new Swiper.Swiper("#carouselExampleIndicators", {
            slidesPerView: 1,
            spaceBetween: 30,
            loop: true,
            navigation: {
                nextEl: '.swiper-button-next',
                prevEl: '.swiper-button-prev',
            },
            observer: true,  
            observeParents: true,
        }));
        var b = (new Swiper.Swiper("#my_carousel", {
            loop: true,

            pagination: {
                el: ".swiper-pagination",
            },
        }));
        console.log(a);
        console.log(b);
        
      }));

/*  Not a pure module */
